Задание 8-9
kuzzaka/oleghruschev-entry-project pull request #18
Opened 2018-02-21 10:43 UTC by oleghruschev

2018-02-27 03:52 UTC, kuzzaka requested changes

2018-02-27 03:52 UTC, kuzzaka commented on index.html
> +    <span class="reviews_date modal_p"><%= date %></span>
modal_p - не декларативное название

2018-02-27 03:52 UTC, kuzzaka commented on index.html
> +<script type="template" id="reviews-template">
второй раз тот же шаблон

2018-02-27 03:52 UTC, kuzzaka commented on index.html
> +                          <li><a class="characteristic_a" id="active_a" >характеристики</a></li>
зачем здесь использовать id?

2018-02-27 03:52 UTC, kuzzaka commented on index.html
> +                  <div class="characteristic_nav">
почему не тэг nav?

2018-02-27 03:52 UTC, kuzzaka commented on index.html
> +                                  <span>Индивидуальная упаковка</span><span>Пакет</span>
почему тут не выводится из товара?

2018-02-27 03:52 UTC, kuzzaka commented on index.html
> +                  <div class="reviews_wrap modal_close">
Название класса modal_close не отражает, то что делает. По сути он просто не показывает блок.

2018-02-27 03:52 UTC, kuzzaka commented on index.html
> +                      <div class="reviews  modal ">
я бы не сказал, что отзывы - это модальное окно

2018-02-27 03:52 UTC, kuzzaka commented on index.html
> +                                  <p style="font-size: 1.4rem">Ваша оценка</p>
стили в разметке - это моветон

2018-02-27 03:52 UTC, kuzzaka commented on spec/products-view.spec.js
>      it('call the updateUrl', function() {
описание теста не соответствует тому, что он делает

2018-02-27 03:52 UTC, kuzzaka commented on spec/reviews-view.spec.js
> +        expect(instance.tagName).toBe("div");
в каждом сьюте нужно создавать новый инстанс

2018-02-27 03:52 UTC, kuzzaka commented on src/constructors/reviews-list.js
> +  url: "none"
?

2018-02-27 03:52 UTC, kuzzaka commented on src/constructors/reviews-view.js
> +const reviewsList = new ReviewsList();
инстанс создается в конструкторе

2018-02-27 03:52 UTC, kuzzaka commented on src/constructors/reviews-view.js
> +const AppView = Backbone.View.extend({
второй компонент в одном файле

2018-02-27 03:52 UTC, kuzzaka commented on src/constructors/reviews-view.js
> +const AppView = Backbone.View.extend({
Почему AppView? Вьюха занимается только отзывами

2018-02-27 03:52 UTC, kuzzaka commented on src/constructors/reviews-view.js
> +      reviewsList.on('add', this.addOne, this);
listenTo

2018-02-27 03:52 UTC, kuzzaka commented on src/constructors/reviews-view.js
> +   addOne: function(reviews) {
почему reviews? по идее должна приходить одна модель

2018-02-27 03:52 UTC, kuzzaka commented on src/constructors/reviews-view.js
> +    cancelReviews: function () {
скорее resetInput. Названия методов должны отражать то, что они делают

2018-02-27 03:52 UTC, kuzzaka commented on src/constructors/reviews-view.js
> +      reviewsList.create({
методы не должны работать с внешними переменными

2018-02-27 03:52 UTC, kuzzaka commented on css/style.scss
> +}
много файлов, где нет пустой последней строки

2018-02-27 14:51 UTC, oleghruschev commented on index.html
> +    <span class="reviews_date modal_p"><%= date %></span>
исправил

2018-02-27 14:55 UTC, oleghruschev commented on index.html
> +<script type="template" id="reviews-template">
исправил

2018-02-28 05:18 UTC, oleghruschev commented on index.html
> +                          <li><a class="characteristic_a" id="active_a" >характеристики</a></li>
для изменения цвета активной ссылки, т. к. приоритет id выше

2018-02-28 06:58 UTC, kuzzaka requested changes

2018-02-28 06:58 UTC, kuzzaka commented on css/style.scss
> +.my-class ~ .star_ico:before {
а можно нормально назвать то?

2018-02-28 06:58 UTC, kuzzaka commented on index.html
> +                          <li><a class="characteristic_a" id="active_a" >характеристики</a></li>
Нужно это делать повышением специфичности с помощью классов

2018-03-03 09:16 UTC, closed without merging